INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (1, 'TV LG 32', 94, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (2, 'TV LG 44', 95, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (3, 'TV LG 56', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (4, 'TV LG 21', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (5, 'TV LG 48', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (6, 'TV LG Curve', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (7, 'TV LG 4k 44', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (8, 'TV LG 4k 56', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (9, 'TV LG 4k 48', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (10, 'Equipo sonido LG 100 kw', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (11, 'Equipo sonido LG 200 kw', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (12, 'Equipo sonido LG 1000 kw', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (13, 'Lavadora LG 18 Lb digital', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (14, 'Lavadora LG 21 Lb digital', 99, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (15, 'Lavadora LG 30 Lb digital', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (16, 'Lavadora LG 18 Lb', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (17, 'Lavadora LG 21 Lb', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (18, 'Lavadora LG 30 Lb', 99, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (19, 'Refrigerador LG', 100, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (20, 'Cocina LG', 96, 1, 1)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (21, 'TV SONY 32', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (22, 'TV SONY 44', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (23, 'TV SONY 56', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (24, 'TV SONY 21', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (25, 'TV SONY 48', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (26, 'TV SONY Curve', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (27, 'TV SONY 4K 44', 92, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (28, 'TV SONY 4K 56', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (29, 'TV SONY 4k 48', 99, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (30, 'Equipo sonido SONY 100Kw', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (31, 'Lavadora SONY', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (32, 'Caja sonido SONY', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (33, 'DVD SONY', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (34, 'Monitor SONY', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (35, 'Audifonos SONY', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (36, 'Game pad SONY', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (37, 'Microondas SONY', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (38, 'Ventilador SONY', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (39, 'Licuadora SONY', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (40, 'Microondas 100 W', 100, 1, 2)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (41, 'Cocina Mabe 4 quemadores', 100, 1, 3)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (42, 'Cocina Mabe 6 quemadores', 100, 1, 3)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (43, 'Cocina Mabe 4 quemadores horno', 100, 1, 3)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (44, 'Cocina Mabe 6 quemadores horno', 97, 1, 3)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (45, 'Cocina induccion 4q', 100, 1, 3)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (46, 'Cocina induccion 6q', 100, 1, 3)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (47, 'Cocina induccion 4q horno', 100, 1, 3)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (48, 'Cocina induccion 6q horno', 100, 1, 3)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (49, 'Refri Mabe Cromada 250L', 100, 1, 3)
INSERT dbo.Electrodomestico(idElectrodomestico, nombreElectrodomestico, stockElectrodomestico, idTienda, idProveedor) VALUES (50, 'Refri Mabe Cromada 400L', 100, 1, 3)
